[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solliq_locker = "BmpeD1Hmk1HraMJrxji4fjQNCYHqBGNi2EksPTFt9izC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/solliq_locker"]
types = "target/types"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 120000
shutdown_wait = 2000
upgradeable = false
skip-deploy = true  # Skip deployment since we've already deployed
